### ISSUE TITLE
Show slice indications in the timeline.

### ISSUE THREAD

**Issue by phillbush** [pvpscript/mpv-video-splice#1]
I don't know whether this is possible, but it would be nice to have the start and end times of slices shown on the OSD timeline.  MPV does something like that for video chapters (as in the image), with each chapter boundary identified on the OSD timeline.  The only problem would be identify which mark is a slice start/end time, as all marks look the same.  Would it be possible to differentiate the marks? (Or color/number/identify the region between marks?)

Thanks!

![scrot_2020-12-22-174000](https://user-images.githubusercontent.com/63266536/102931811-fc15c380-4496-11eb-9f2b-88aa2fbdfe12.png)

**Comment by phillbush** [comment]
So, I tried to use chapter indications for slices, and immediately gave up the idea.  
Things get confused with lots of slices, especially when the slices are out of order.  
Here is the code anyway. Just need to call it every time `times` is changed.

```lua
local function reset_chapters()
	local chapters = {}

	for i, obj in ipairs(times) do
		table.insert(chapters, {
			title = string.format("Slice %d start", i),
			time = obj.t_start
		})
		table.insert(chapters, {
			title = string.format("Slice %d end", i),
			time = obj.t_end
		})
	end
	mp.set_property_native("chapter-list", chapters)
end
```

**Comment by pvpscript** [comment]
I was just looking up the documentation to see if that was possible, but apparently you've already came up with a solution :p

Pretty neat!
