### ISSUE TITLE
How to make it work in Windows

### ISSUE THREAD

**Issue by ScribbleGhost** [pvpscript/mpv-video-splice#2]
Is this supposed to work with Windows? I would absolutely love to use it together with [mpv](https://mpv.io/installation/), but I can't get it to export. I have already added ffmpeg to PATH.

Any ideas what I can do to get it to work?

**Comment by pvpscript** [comment]
This wasn't made with Windows in mind, but you can check out [this fork](https://github.com/Pullusb/mpv-video-splice) which makes it work on Windows.
