### ISSUE TITLE
Specifying output directory from config file instead of environment variables

### ISSUE THREAD

**Issue by aplatti** [pvpscript/mpv-video-splice#3]
Hi!  I love this plugin.   I'm wondering if I can specify my output directory from a configuration file or script, instead of from an environment variable.  I'm on a mac and launching MPV from the finder when I double click a video file, and the OS does not seem to load a shell, so the environment variables aren't seen.   I'm not really familiar with the MPV scripting, and I was trying to avoid editing the mpv-splice.lua file directly.   Thanks!

**Comment by pvpscript** [comment]
It's doable! I'll do it as soon as I have some free time.

Edit: I just saw your pull request! Thanks for contributing! :)
