### ISSUE TITLE
Simple mod to output timecodes in SRT format for subtitles

### ISSUE THREAD

**Issue by korakinos** [pvpscript/mpv-video-splice#7]
This is not a bug report or feature request -- sorry for misusing the tracker and feel free to close this immediately --, just something pvpscript or other people might find interesting. Long story short, [I modified this script a little](https://github.com/korakinos/mpv-video-splice) in order to produce output in valid SRT format.

While I was looking for a way to produce an [SRT subtitle file](https://en.wikipedia.org/wiki/Subrip) without too much manual editing, I came across mpv-video-splice and noticed that its "print slices" output (Alt+P) is already pretty close to being valid SRT. So I modified the code a little, added a function write_srt() and a new keybinding Alt+W to wrint all recorded timestamps to an SRT file, sorted chronologically. Existing SRT files are backed up (in case I hit Alt+W by mistake). A side effect of my changes is that timecode precision is increased by one digit.

This is how the output looks like:

```
1
00:00:00,567 --> 00:00:00,767
{}

2
00:00:01,367 --> 00:00:01,567
{}

3
00:00:01,867 --> 00:00:02,033
{}
```

The "{}"s are placeholders for the actual text. I chose "{}" because it is already a default selector syntax for string.format() in python, and I used a small python script to merge the SRT template generated by the mpv/lua script with a plain text file of the actual subtitles. My python script (which for the most part is busy reading paragraphs from the text file) looks like this:

```python
paragraphs = []

# parse text paragraphs
with open("subtitles.txt") as text_file:
    paragraph = ""
    for line in text_file:
        if line.isspace():
            # save finished paragraph, if not empty
            if (paragraph and not paragraph.isspace()):
                paragraphs.append(paragraph)
            paragraph = ""
        else:
            # continue assembling paragraph
            paragraph += line

with open("subtitles-template.srt") as template_file:
    with open("subtitles.srt", "w") as merged_file:
        srt_data = template_file.read()
        merged_file.write(srt_data.format(*paragraphs))
```

I am not suggesting that any of this functionality should be part of mpv-video-splice, as video splicing and subtitling are two quite diffferent tasks. In fact, maybe I will make a derived script as a pure subtitling tool. For now, I am just sharing the story of this mod here and the modded code in [my fork](https://github.com/korakinos/mpv-video-splice).

**Comment by korakinos** [comment]
I have now stripped the video editing function out of my fork, added the python script to my repo and renamed it to mpv-srt-tools. May somebody some day find it as useful as I did. On that occasion, many thanks to pvpscript!

**Comment by pvpscript** [comment]
I'm really sorry. Work has been keeping me so busy for the past semester that I completely missed your story. Anyway, thanks for posting it! I'm really glad my code served as inspiration for you to create your own.
Keep it up!
