### ISSUE TITLE
a nill value

### ISSUE THREAD

**Issue by nobef** [pvpscript/mpv-video-splice#8]
Here is such an error
![изображение](https://user-images.githubusercontent.com/77186394/185262779-8bce5355-7346-4ea4-8767-63fc4ef7cd55.png)

**Comment by apiszcz** [comment]
Same error, appears it does not support windows?

**Comment by pvpscript** [comment]
Hello people, I'm sorry about the very late response... I'm picking up this project again and will be working on making it compatible with Windows. https://github.com/pvpscript/mpv-video-splice/issues/12

**Comment by pvpscript** [comment]
It should work on Windows now, hopefully! :smiley:
